            version: '3.8'

            services:
              db:
                image: mysql:8.0
                restart: always
                environment:
                  MYSQL_ROOT_PASSWORD: wordpress
                  MYSQL_PASSWORD: wordpress
                  MYSQL_USER: wordpress
                  MYSQL_DATABASE: wordpress
                volumes:
                  - db_data:/var/lib/mysql
                networks:
                  - wordpress_net

              wordpress:
                image: wordpress:latest
                restart: always
                environment:
                  WORDPRESS_DB_HOST: db:3306
                  WORDPRESS_DB_USER: wordpress
                  WORDPRESS_DB_NAME: wordpress
                  WORDPRESS_DB_PASSWORD: wordpress
                ports:
                  - "8080:80"
                networks:
                  - wordpress_net

            volumes:
              db_data:

            networks:
              wordpress_net:
